baseurl = "/"
languageCode = "ja-jp"
title = "i was perfect"
publishdir = "docs"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true


[params]
  # Sets the meta tag description
  description          = "@515hikaruの技術ブログ"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "I WAS PERFECT"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/post/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtBottom    = false
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = true
  socialShareFacebook  = true
  socialShareReddit    = true
  socialShareLinkedin  = true
  socialShareStumbleupon = true
  socialSharePinterest = true
  socialShareEmail     = false

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]

  # options for highlight.js (version, additional languages, and theme)
  disable_highlight = false # set to true to disable Highlight
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "css"]
  highlightjsTheme = "github"
  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "I WAS PERFECT"

  paragraph = ""

  about     = ""

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo.jpg"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = true
    width     = ""
    alt       = "Hugo Future Imperfect"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 3

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github           = "515hikaru"
  gitlab           = "515hikaru"
  bitbucket        = "tkojima28"
  medium           = "515hikaru"
  # Professional/Business Oriented Communities
  twitter          = "515hikaru"
  # Email
  email            = "12kojima.takahiro@gmail.com"
